### ISSUE TITLE
build/intermediates/aceso not be produced?

### ISSUE THREAD

**Issue by SivanLiu** [meili/Aceso#1]
when I run the aceso-demo with the gradlew clean assembleRelease command .I have not find the build/intermediates/aceso,Why is it ?

**Comment by guoguo338** [comment]
Can assembleDebug run well? Could you pls. paste the wrongly log with 'gradlew assembleRelease ---stacktrace'?

**Comment by farmerjohngit** [comment]
@YaFengYi  If you fail to execute the ‘assembleRelease’, please pull the code again, or sure the dir is under app module: app/build/intermediates/aceso

**Comment by SivanLiu** [comment]
@farmerjohngit thanks,I try it
