### ISSUE TITLE
能否有方法判断是否已经修复过呢

### ISSUE THREAD

**Issue by 317764920** [meili/Aceso#10]
使用versionCode能否判断，例如当前app的versionvode=1，修复时将versioncode=2，下发fix-apk时判断用户当前app的versioncode和fix-apk的versioncode吗？

**Comment by farmerjohngit** [comment]
@317764920   变量标记＋持久化 就好了啊。

**Comment by 317764920** [comment]
@farmerjohngit 好的 ，我就是想的可能需要服务端来做这个标记
