### ISSUE TITLE
新建fix工程要不要把所有类都拷贝过去

### ISSUE THREAD

**Issue by zlg2338781286** [meili/Aceso#17]
我新建fix工程，只拷贝要修改的类到fix工程中，由于修改的类中有引入其他类，在编译的时候报错，这个怎么解，需要把所有的类都拷贝到fix工程吗？
Execution failed for task ':businessHall:compileDebugJavaWithJavac'.
> Compilation failed; see the compiler error output for details.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED

Total time: 9.921 secs
localhost:Cmcc_aceso_fix apple$ gradle acesoDebug
To honour the JVM settings for this build a new JVM will be forked. Please consider using the daemon: https://docs.gradle.org/2.14.1/userguide/gradle_daemon.html.
Incremental java compilation is an incubating feature.
blackList file is /Users/apple/android-work/Cmcc_aceso_fix/businessHall/aceso-blacklist.txt
next we will add all-classes.jar to the localJars.
the length of the array before and after comparison:  0 -> 1
next will be aceso fix.
next we will add all-classes.jar to the localJars.
the length of the array before and after comparison:  0 -> 1
next will be aceso fix.
find transform. class: class com.android.build.gradle.internal.transforms.DexTransform. task name: transformClassesWithDexForDebug
:businessHall:preBuild UP-TO-DATE
:businessHall:preDebugBuild UP-TO-DATE
:businessHall:checkDebugManifest
:businessHall:preReleaseBuild UP-TO-DATE
:businessHall:prepareComAndroidSupportAnimatedVectorDrawable2520Library UP-TO-DATE
:businessHall:prepareComAndroidSupportAppcompatV72520Library UP-TO-DATE
:businessHall:prepareComAndroidSupportSupportCompat2520Library UP-TO-DATE
:businessHall:prepareComAndroidSupportSupportCoreUi2520Library UP-TO-DATE
:businessHall:prepareComAndroidSupportSupportCoreUtils2520Library UP-TO-DATE
:businessHall:prepareComAndroidSupportSupportFragment2520Library UP-TO-DATE
:businessHall:prepareComAndroidSupportSupportMediaCompat2520Library UP-TO-DATE
:businessHall:prepareComAndroidSupportSupportV42520Library UP-TO-DATE
:businessHall:prepareComAndroidSupportSupportVectorDrawable2520Library UP-TO-DATE
:businessHall:prepareDebugDependencies
:businessHall:compileDebugAidl UP-TO-DATE
:businessHall:compileDebugRenderscript UP-TO-DATE
:businessHall:generateDebugBuildConfig UP-TO-DATE
:businessHall:generateDebugResValues UP-TO-DATE
:businessHall:generateDebugResources UP-TO-DATE
:businessHall:mergeDebugResources UP-TO-DATE
:businessHall:processDebugManifest UP-TO-DATE
:businessHall:processDebugResources UP-TO-DATE
:businessHall:generateDebugSources UP-TO-DATE
:businessHall:incrementalDebugJavaCompilationSafeguard UP-TO-DATE
:businessHall:compileDebugJavaWithJavac
:businessHall:compileDebugJavaWithJavac - is not incremental (e.g. outputs have changed, no previous execution, etc.).
/Users/apple/android-work/Cmcc_aceso_fix/businessHall/src/main/java/com/businesshall/activity/SettingsActivity.java:48: 错误: 找不到符号
        setContentView(R.layout.activity_settings);
                               ^
  符号:   变量 activity_settings
  位置: 类 layout
/Users/apple/android-work/Cmcc_aceso_fix/businessHall/src/main/java/com/businesshall/activity/SettingsActivity.java:54: 错误: 找不到符号
        tb_notification = (ToggleButton) findViewById(R.id.tb_notification);
                                                          ^
  符号:   变量 tb_notification
  位置: 类 id
/Users/apple/android-work/Cmcc_aceso_fix/businessHall/src/main/java/com/businesshall/activity/SettingsActivity.java:55: 错误: 找不到符号
        password_layout = (RelativeLayout) findViewById(R.id.password_layout);
                                                            ^
  符号:   变量 password_layout
  位置: 类 id
/Users/apple/android-work/Cmcc_aceso_fix/businessHall/src/main/java/com/businesshall/activity/SettingsActivity.java:56: 错误: 找不到符号
        message_layout = (RelativeLayout) findViewById(R.id.message_layout);
                                                           ^
  符号:   变量 message_layout
  位置: 类 id
/Users/apple/android-work/Cmcc_aceso_fix/businessHall/src/main/java/com/businesshall/activity/SettingsActivity.java:57: 错误: 找不到符号
        update_layout = (RelativeLayout) findViewById(R.id.update_layout);
                                                          ^
  符号:   变量 update_layout
  位置: 类 id
/Users/apple/android-work/Cmcc_aceso_fix/businessHall/src/main/java/com/businesshall/activity/SettingsActivity.java:58: 错误: 找不到符号
        faq_layout = (RelativeLayout) findViewById(R.id.faq_layout);
                                                       ^
  符号:   变量 faq_layout
  位置: 类 id
/Users/apple/android-work/Cmcc_aceso_fix/businessHall/src/main/java/com/businesshall/activity/SettingsActivity.java:59: 错误: 找不到符号
        about_layout = (RelativeLayout) findViewById(R.id.about_layout);
                                                         ^
  符号:   变量 about_layout
  位置: 类 id
/Users/apple/android-work/Cmcc_aceso_fix/businessHall/src/main/java/com/businesshall/activity/SettingsActivity.java:60: 错误: 找不到符号
        change_account = (RelativeLayout) findViewById(R.id.change_account);
                                                           ^
  符号:   变量 change_account
  位置: 类 id
/Users/apple/android-work/Cmcc_aceso_fix/businessHall/src/main/java/com/businesshall/activity/SettingsActivity.java:61: 错误: 找不到符号
        change_environment = (RelativeLayout) findViewById(R.id.change_environment);
                                                               ^
  符号:   变量 change_environment
  位置: 类 id
/Users/apple/android-work/Cmcc_aceso_fix/businessHall/src/main/java/com/businesshall/activity/SettingsActivity.java:62: 错误: 找不到符号
        pluginmanager_layout = (RelativeLayout) findViewById(R.id.pluginmanager_layout);
                                                                 ^
  符号:   变量 pluginmanager_layout
  位置: 类 id
/Users/apple/android-work/Cmcc_aceso_fix/businessHall/src/main/java/com/businesshall/activity/SettingsActivity.java:63: 错误: 找不到符号
        rl_look_old_db= (RelativeLayout) findViewById(R.id.rl_look_old_db);
                                                          ^
  符号:   变量 rl_look_old_db
  位置: 类 id
/Users/apple/android-work/Cmcc_aceso_fix/businessHall/src/main/java/com/businesshall/activity/SettingsActivity.java:64: 错误: 找不到符号
        rl_look_new_db= (RelativeLayout) findViewById(R.id.rl_look_new_db);
                                                          ^
  符号:   变量 rl_look_new_db
  位置: 类 id
/Users/apple/android-work/Cmcc_aceso_fix/businessHall/src/main/java/com/businesshall/activity/SettingsActivity.java:65: 错误: 找不到符号
        rl_local_test= (RelativeLayout) findViewById(R.id.rl_local_test);
                                                         ^
  符号:   变量 rl_local_test
  位置: 类 id
/Users/apple/android-work/Cmcc_aceso_fix/businessHall/src/main/java/com/businesshall/activity/SettingsActivity.java:81: 错误: 找不到符号
        tv_commonback = (ImageView) findViewById(R.id.tv_commonback);
                                                     ^
  符号:   变量 tv_commonback
  位置: 类 id
/Users/apple/android-work/Cmcc_aceso_fix/businessHall/src/main/java/com/businesshall/activity/SettingsActivity.java:82: 错误: 找不到符号
        tv_commontitle = (TextView) findViewById(R.id.tv_commontitle);
                                                     ^
  符号:   变量 tv_commontitle
  位置: 类 id
/Users/apple/android-work/Cmcc_aceso_fix/businessHall/src/main/java/com/businesshall/activity/SettingsActivity.java:83: 错误: 找不到符号
        has_update = (ImageView) findViewById(R.id.has_update);
                                                  ^
  符号:   变量 has_update
  位置: 类 id
/Users/apple/android-work/Cmcc_aceso_fix/businessHall/src/main/java/com/businesshall/activity/SettingsActivity.java:84: 错误: 找不到符号
        item_loginout = (LinearLayout) findViewById(R.id.item_loginout);
                                                        ^
  符号:   变量 item_loginout
  位置: 类 id
/Users/apple/android-work/Cmcc_aceso_fix/businessHall/src/main/java/com/businesshall/activity/SettingsActivity.java:148: 错误: 找不到符号
            case R.id.password_layout:
                     ^
  符号:   变量 password_layout
  位置: 类 id
/Users/apple/android-work/Cmcc_aceso_fix/businessHall/src/main/java/com/businesshall/activity/SettingsActivity.java:153: 错误: 找不到符号
            case R.id.message_layout:
                     ^
  符号:   变量 message_layout
  位置: 类 id
/Users/apple/android-work/Cmcc_aceso_fix/businessHall/src/main/java/com/businesshall/activity/SettingsActivity.java:158: 错误: 找不到符号
            case R.id.update_layout:
                     ^
  符号:   变量 update_layout
  位置: 类 id
/Users/apple/android-work/Cmcc_aceso_fix/businessHall/src/main/java/com/businesshall/activity/SettingsActivity.java:164: 错误: 找不到符号
            case R.id.faq_layout:
                     ^
  符号:   变量 faq_layout
  位置: 类 id
/Users/apple/android-work/Cmcc_aceso_fix/businessHall/src/main/java/com/businesshall/activity/SettingsActivity.java:167: 错误: 找不到符号
            case R.id.about_layout:
                     ^
  符号:   变量 about_layout
  位置: 类 id
/Users/apple/android-work/Cmcc_aceso_fix/businessHall/src/main/java/com/businesshall/activity/SettingsActivity.java:170: 错误: 找不到符号
            case R.id.item_loginout:
                     ^
  符号:   变量 item_loginout
  位置: 类 id
/Users/apple/android-work/Cmcc_aceso_fix/businessHall/src/main/java/com/businesshall/activity/SettingsActivity.java:176: 错误: 找不到符号
            case R.id.change_account:
                     ^
  符号:   变量 change_account
  位置: 类 id
/Users/apple/android-work/Cmcc_aceso_fix/businessHall/src/main/java/com/businesshall/activity/SettingsActivity.java:180: 错误: 找不到符号
            case R.id.change_environment:
                     ^
  符号:   变量 change_environment
  位置: 类 id
/Users/apple/android-work/Cmcc_aceso_fix/businessHall/src/main/java/com/businesshall/activity/SettingsActivity.java:183: 错误: 找不到符号
            case R.id.tv_commonback:
                     ^
  符号:   变量 tv_commonback
  位置: 类 id
/Users/apple/android-work/Cmcc_aceso_fix/businessHall/src/main/java/com/businesshall/activity/SettingsActivity.java:186: 错误: 找不到符号
            case R.id.pluginmanager_layout:
                     ^
  符号:   变量 pluginmanager_layout
  位置: 类 id
/Users/apple/android-work/Cmcc_aceso_fix/businessHall/src/main/java/com/businesshall/activity/SettingsActivity.java:189: 错误: 找不到符号
            case R.id.tb_notification:
                     ^
  符号:   变量 tb_notification
  位置: 类 id
/Users/apple/android-work/Cmcc_aceso_fix/businessHall/src/main/java/com/businesshall/activity/SettingsActivity.java:197: 错误: 找不到符号
            case R.id.rl_look_new_db:
                     ^
  符号:   变量 rl_look_new_db
  位置: 类 id
/Users/apple/android-work/Cmcc_aceso_fix/businessHall/src/main/java/com/businesshall/activity/SettingsActivity.java:202: 错误: 找不到符号
            case R.id.rl_look_old_db:
                     ^
  符号:   变量 rl_look_old_db
  位置: 类 id
/Users/apple/android-work/Cmcc_aceso_fix/businessHall/src/main/java/com/businesshall/activity/SettingsActivity.java:207: 错误: 找不到符号
            case R.id.rl_local_test:
                     ^
  符号:   变量 rl_local_test
  位置: 类 id
31 个错误

**Comment by guoguo338** [comment]
不需要的，配置下    allClassesJar 即可，可以参考下readme。

**Comment by zlg2338781286** [comment]
@guoguo338 
这个我看过的，路径什么的我都配置好了，也打印出来看了，路径没有错，可是还不行。是打的release版，黑名单，混淆两边都开着的

**Comment by farmerjohngit** [comment]
@zlg2338781286 
1.  检查下fix工程中 SettingsActivity.java import的R有没有被ide修改。　
2. 检查下指定的allClassesJar 中是否有对应的R

**Comment by zlg2338781286** [comment]
@guoguo338 @farmerjohngit 我把R引用到的资源都拷贝过来了，不会报错了，打出了包，但是修复的东西没出现，前前后后也检查了几遍，没发现有出错的地方，这就有点尴尬了

**Comment by guoguo338** [comment]
@zlg2338781286 ， 可以反编译看下你的allclasses.jar是否有那些变量？

**Comment by farmerjohngit** [comment]
你按我说的两个步骤检查一下。  不需要把资源拷贝过来的。

**Comment by farmerjohngit** [comment]
@zlg2338781286  另外你是说 修复没生效？加了FixMtd注解没

**Comment by zlg2338781286** [comment]
@farmerjohngit 加FixMtd了，那我反编译一下看看，如果没有这些变量怎么办

**Comment by zlg2338781286** [comment]
@farmerjohngit 我看了下，allclassjar中没有R，像findviewbyId这种里面是编译好的常量值了，引用中没有引用R文件，这怎么弄

**Comment by farmerjohngit** [comment]
@zlg2338781286 你工程中有用到其他的什么插件？ 比如说ThinRPlugin?

**Comment by zlg2338781286** [comment]
@farmerjohngit 有用到依赖注入neenbedankt

**Comment by farmerjohngit** [comment]
@zlg2338781286  能否提供一个demo工程？

**Comment by zlg2338781286** [comment]
@farmerjohngit 
[networkDemo.zip](https://github.com/meili/Aceso/files/813035/networkDemo.zip)

**Comment by zlg2338781286** [comment]
[NetworkDemo_fix.zip](https://github.com/meili/Aceso/files/813046/NetworkDemo_fix.zip)

**Comment by zlg2338781286** [comment]
@farmerjohngit 根据我的demo有发现什么吗

**Comment by farmerjohngit** [comment]
@zlg2338781286  你只提供了fix工程 没有demo工程

**Comment by zlg2338781286** [comment]
@farmerjohngit 发了呀，可能是因为误点一次close你那边没显示，我再发一次

**Comment by zlg2338781286** [comment]
[networkDemo.zip](https://github.com/meili/Aceso/files/815642/networkDemo.zip)
@farmerjohngit

**Comment by farmerjohngit** [comment]
@zlg2338781286  两个问题。
1.fix工程中不能带额外的资源
2.fix工程的manifest只能有一个application标签（参考demo-fix）

**Comment by farmerjohngit** [comment]
@zlg2338781286  感谢提供信息，  相关说明已更新到[wiki](https://github.com/meili/Aceso/wiki)

**Comment by zlg2338781286** [comment]
@farmerjohngit 有看过这个demo吗

**Comment by farmerjohngit** [comment]
嗯
