### ISSUE TITLE
对发布包进行360加固或者腾讯加固后是否还可以进行热修复？

### ISSUE THREAD

**Issue by jiguanghover** [meili/Aceso#18]
对发布包进行360加固或者腾讯加固后release包发布，当发现问题时，是否可以用aceso进行修复？

**Comment by guoguo338** [comment]
理论上来说不会的，因为360加固是"把所有的java方法换成natvie实现，再在natvie层做逻辑混淆，和虚拟机指令集替换。" -- Andy Zhang。而Aceso是基于.class级别做的，360加固对Aceso理论上是透明的。

**Comment by guoguo338** [comment]
加固方案一般是在dex/res上包了一层壳，最后还是要走到虚拟机去执行的，加固方案是不能改变原来的执行方式的，Aceso是asm注入.class，这些注入代码肯定最后会被正常调用到。
