### ISSUE TITLE
sure you aceso-mapping is right and no new method

### ISSUE THREAD

**Issue by weiyuant** [meili/Aceso#25]
the method ：isCropSupported Z in class com/spdbccc/app/menu/activity/scan/code/a/e not found in the aceso-mapping sure you aceso-mapping is right and no new method 这是什么问题，生成宿主apk时isCropSupported方法让proguard去除掉了，生成fix时就报上面问题

**Comment by xiejinsorry** [comment]
你们解决了没有？在修复工程 proguard -applymapping D:\mapping\aceso-mapping.txt不起作用啊？

**Comment by zlg2338781286** [comment]
fix工程中所有的资源都要删掉，删掉后还这样吗

**Comment by xiejinsorry** [comment]
删了 只留 了 manifest 而已 res 下面的 文件夹全部删了

**Comment by weiyuant** [comment]
请教一下，fix生成的包包含去除黑名单的所有类？可以只生成修改的类吗
