### ISSUE TITLE
Error:Execution failed for task ':app:transformClassesWithDexForDebug'. > java.util.zip.ZipException: duplicate entry: com/android/tools/fd/runtime/AbstractPatchesLoaderImpl.class

### ISSUE THREAD

**Issue by jasonlu0117** [meili/Aceso#27]
宿主工程编译debug版本时，编译出错，

Error:Execution failed for task ':app:transformClassesWithDexForDebug'.
java.util.zip.ZipException: duplicate entry: com/android/tools/fd/runtime/AbstractPatchesLoaderImpl.class
这个该如何解决？

**Comment by farmerjohngit** [comment]
clean 以后重新试试，如果还是不行，检查下有没有重复依赖aceso-lib库

**Comment by jasonlu0117** [comment]
clean以后还是不行，应该没有重复依赖，把instrumentDebug为false就能编译通过，改为true就报这个错

**Comment by jasonlu0117** [comment]
问题已解决。与instant run有关。
http://stackoverflow.com/questions/38348665/unable-to-instantiate-application-com-android-tools-fd-runtime-bootstrapapplicat
