### ISSUE TITLE
有几个疑问

### ISSUE THREAD

**Issue by xiejinsorry** [meili/Aceso#28]
白天的问题都解决了，clean rebuild 就好了，现在有几个新的问题
1. new Aceso().installPatch(optDir, patchFile); 这个patchFile的路径是什么？我可以用demo上的吗?
2.如果我要修复的版本要有资源上的问题怎么办？能修复吗？如何修复
3.比如我从我后台下载了一个修复apk,我是不是每次启动都要installPatch一下？不然就没办法使用？

**Comment by farmerjohngit** [comment]
1.patchFile 就是fix工程生成的patch包
2.不支持
3.是的
