### ISSUE TITLE
patch apk中无patch内容

### ISSUE THREAD

**Issue by ghost** [meili/Aceso#29]
首先给个👍，东西挺好的。wiki上的教程略简单，req上解答的问题，在wiki上或者demo上无法明显体现出来。
我这边碰到一个问题，debug和release式下都有输出一个apk,但是解开发现没有我要的patch，是android/support/multidex。

**Comment by farmerjohngit** [comment]
`但是解开发现没有我要的patch，是android/support/multidex。`

fix工程生成的patch文件只有中只有multidex的class?

fix工程开了multidex吗？

**Comment by ghost** [comment]
@farmerjohngit 是开了multidex，除了android/support/multidex，当然也有AppPachesLoaderImpl.class。如果关闭multidex,  就会报错，错误信息参考log。

[log.txt.zip](https://github.com/meili/Aceso/files/827199/log.txt.zip)

也在fix project的混淆文件是复制host project的，文件内增加了-applymapping mapping.txt

**Comment by farmerjohngit** [comment]
这是proguard shinker的问题。 http://stackoverflow.com/questions/32770981/proguard-error-the-output-jar-is-empty-did-you-specify-the-proper-keep-opti

**Comment by ghost** [comment]
-keep public class * {
    public protected <fields>;
    public protected <methods>;
}

简单添加了上面这句话看到patch有了
