### ISSUE TITLE
局限性太大，基本微信tinker出来后其他开源热修复框架就没啥用了

### ISSUE THREAD

**Issue by hanhailong** [meili/Aceso#3]
局限性太大，基本微信tinker出来后其他开源热修复框架就没啥用了，不过可以作为学习借鉴一下！！！

**Comment by guoguo338** [comment]
tinker是提供了一个热部署的方向，instantRun注入方式是另外一个方向。你说的局限性太大能否详细说下？

**Comment by guoguo338** [comment]
你指的应该是Aceso只能修复方法内部的函数体？Aceso瞄准的是轻量化的“热”修复，能满足90%以上的需求。Tinker比较重，包括需要合成Dex，做全量OAT，全量的Resource merge等，对磁盘空间要求比较高。Tinker其实更适合做功能性的更新。蘑菇街这边也是接了Tinker来做类似动态部署的事情的。具体你可以看下文章 https://github.com/meili/Aceso/wiki/Mogujie_android_hotfix_exploration。

当然，业界方案层出不穷，选择适合自己的就行。

**Comment by hanhailong** [comment]
局限性是相对tinker来说的，tinker能修复dex、library和resources，缺点是必须得重启，不能实时生效

**Comment by guoguo338** [comment]
修复resources/library这种instantRun方案也支持的，不是重点的技术点。

**Comment by guoguo338** [comment]
相对Tinker, Aceso有几个优势，
1. 轻IO。
2. 下载即生效。
3. ASM方式注入，天然的适配性好，做HotFix／部署方案最头疼的就是适配各个厂商的ROM了(以前做Atlas的时候，天天折腾各种适配问题很是头疼)，Tinker那边其实也一直在解各种适配问题。

不知道这个回答是否能解答你的问题？

**Comment by hanhailong** [comment]
赞，各有优缺点，看自己项目需要了

**Comment by guoguo338** [comment]
其实天然适配性好是蘑菇街选择InstantRun方案的一个最大的驱动力了，HotFix方案本身的极致稳定是我们追求的目标。
