### ISSUE TITLE
mapping.txt这个是自动生成的吗？

### ISSUE THREAD

**Issue by umeitime** [meili/Aceso#30]
Error:Execution failed for task ':app:transformClassesWithDexForUmeitimeRelease'.
> java.io.FileNotFoundException: /Users/hujunwei/Desktop/AndroidStudioProjects/weeyuu/app/build/outputs/mapping/umeitime/release/mapping.txt (No such file or directory)

**Comment by umeitime** [comment]
我这边生成不了

**Comment by Sss1986** [comment]
混淆后就会生成..   现在他制作补丁. 我这里有点问题.

**Comment by farmerjohngit** [comment]
mapping.txt是混淆的产出文件，开了混淆就会生成

**Comment by umeitime** [comment]
我这边只生成了dump.txt和seeds.txt 我开启了混淆了。

**Comment by farmerjohngit** [comment]
按模版提问吧 https://github.com/meili/Aceso/wiki/Issue-Format
