### ISSUE TITLE
java.lang.ClassNotFoundException: com.android.tools.fd.runtime.AppPatchesLoaderImpl

### ISSUE THREAD

**Issue by huxibao** [meili/Aceso#33]
运行时出现 上述错误，在lib中没看到这个类 。这个怎么解决

**Comment by farmerjohngit** [comment]
检查打出的patch包中有没有这个类

**Comment by ghost** [comment]
看一下是不是targetSdkVersion大于23，如果大于23，并且你的patch文件不是在自己包下面的目录，那么需要文件读取权限的。

**Comment by gpisjustme** [comment]
这个路径下的确没有这个类啊  lib中都没有

**Comment by gpisjustme** [comment]
如何能解决这个问题  希望楼主给个方案

**Comment by farmerjohngit** [comment]
@gpisjustme 打出的patch包里面没有这个类？

**Comment by gpisjustme** [comment]
需要反编译apk看吗

**Comment by farmerjohngit** [comment]
是的

**Comment by gpisjustme** [comment]
这个对gradle版本有要求吗

**Comment by farmerjohngit** [comment]
@gpisjustme  android gradle插件暂时只支持2.0.0－2.2.3

**Comment by gpisjustme** [comment]
只是被混淆，没有被插桩的类会不会在allClassesJar里面？这个的目的是什么

**Comment by farmerjohngit** [comment]
会的。什么目的

**Comment by gpisjustme** [comment]
好的 我再试试  宿主和补丁的gradle版本号不一样也可以吧

**Comment by farmerjohngit** [comment]
嗯
