### ISSUE TITLE
第三方aar或者jar包里的方法可以热更新吗

### ISSUE THREAD

**Issue by gpisjustme** [meili/Aceso#35]
通过改框架，rt

**Comment by farmerjohngit** [comment]
可以的。

**Comment by gpisjustme** [comment]
但是我们一般拿不到第三方的mapping文件哦，所以无法更新？有没有别的什么方法

**Comment by farmerjohngit** [comment]
你打包的时候产出的mapping文件是包括所有打进apk的类的，你可以看看

**Comment by gpisjustme** [comment]
我的意思是 第三方已经自己混淆过一次了  这种情况  拿不到他混淆的mapping文件吧

**Comment by farmerjohngit** [comment]
那当然，， 如果你源文件都没有那也用不了热修复
