### ISSUE TITLE
你们那个fix工程怎么编译成apk呢？

### ISSUE THREAD

**Issue by IdealMiracle** [meili/Aceso#38]
gradle/.gradlew acesoRelease 这个应该是对应linux下的命令 
我用的windows 直接运行那个gradlew.bat显示编译成功 但是没有apk生成
直接用Android studio编译不了 你们的工程有报错不是完全的工程
请问这种怎么解决呢？谢谢

**Comment by farmerjohngit** [comment]
fix工程下，app/build/output/apk 目录没有apk文件生成？

**Comment by IdealMiracle** [comment]
嗯 是的没有apk生成

**Comment by IdealMiracle** [comment]
弄好了 谢谢
