### ISSUE TITLE
在mac上跑Demo时无法找到Aceso的类和R类

### ISSUE THREAD

**Issue by Dawnton** [meili/Aceso#4]
我直接在mac中跑的原生demo-fix,但是编译时提示无法找到Aceso的类和R类,可能是build.gradle中路径配置的不对,请问具体该怎么配置呢?还有mac上的gradlew命令为./grdlew acesoDebug??

**Comment by guoguo338** [comment]
能否贴下Log?

**Comment by Dawnton** [comment]
./gradlew acesoDebug
./gradlew: line 159: _OPTS: command not found
错误: 找不到或无法加载主类 +x

**Comment by farmerjohngit** [comment]
@Dawnton  你这是gradle 的环境没配好啊。。  如果你已经装好了gralde,则在fix工程根目录执行gradle init，然后再执行命令。

**Comment by Dawnton** [comment]
刚才是gradlew文件搞错了,现在是这种情况

/Users/dawnton/Downloads/Aceso-master/aceso-demo-fix/app/src/main/java/com/mogujie/aceso/demo/MainActivity.java:46: 错误: 找不到符号
        new Aceso().installPatch(optDir, patchFile);
            ^
  符号:   类 Aceso
  位置: 类 MainActivity
1 个错误

**Comment by farmerjohngit** [comment]
@Dawnton fix工程有改过吗

**Comment by Dawnton** [comment]
把原来的项目删了   重新跑了一遍  好了
debug时 应该是这样 instrumentDebug = true  否则build文件夹下不会生成aceso所需的更新文件
还有就是需要在修改的类中千万别手贱把原来的类导入的报红的包名给删掉了(问题产生的原因就是这个)

谢谢开发人员的耐心解答
