### ISSUE TITLE
“在Fix工程中切出一个单独的分支”这是什么意思？

### ISSUE THREAD

**Issue by Jekris** [meili/Aceso#44]
我对A类进行了修复，也修复成功了，但是我第二次又再次修改这个A类，那我应该怎么操作？看了Wiki里面说的“在Fix工程中切出一个单独的分支”，不是很明白什么意思。

如果重新在fix工程执行命令：gradle acesoRelease ，就会报以下的错误：
* What went wrong:
Execution failed for task ':app:packageRelease'.
> java.io.FileNotFoundException: ~\AcesoFixDemo\app\build\outputs\apk\app-release-unsigned.apk (另一个程序正在使用此文件，进程无法访问。)

本来打算clean一下这个工程，就会出现下面的错误：
Error:Execution failed for task ':app:clean'.
> Unable to delete file: ~\AcesoFixDemo\app\build\intermediates\aceso\merged\release\fix-merged.jar

那我应该怎么进行多次修复？

**Comment by farmerjohngit** [comment]
尝试执行gradle --stop 把gradle进程干死，再试试
