### ISSUE TITLE
已加载生成 fix.dex

### ISSUE THREAD

**Issue by Born2PushLimits** [meili/Aceso#45]
debug打版
instrumentDebug = false
使用fixdemo生成fix.apk，推到sdcard中，已经加载生成dex，但是依旧没有修复

**Comment by Born2PushLimits** [comment]
com.android.tools.build:gradle:2.3.3 gradle 版本

**Comment by farmerjohngit** [comment]
文档有误，调试debug版本正确的写法是 instrumentDebug = true
