### ISSUE TITLE
Bug project.applicationVariants.all  找不到all()方法

### ISSUE THREAD

**Issue by wuming2** [meili/Aceso#46]
android.applicationVariants.all Error:Cannot invoke method all() on null object

项目中多Flavor编译，然后报这个错误~ 
后来自己调试plugin，
def android = project.extensions.getByType(AppExtension);
ok了，牵扯到
AcesoHostPlugin  GradleUtil 两个类

**Comment by farmerjohngit** [comment]
可以将你的改动提个pull request,共建~
