### ISSUE TITLE
hostModule编译时出现异常

### ISSUE THREAD

**Issue by 317764920** [meili/Aceso#7]
Information:Gradle tasks [:app:assembleFullDebug]
Warning:The `android.dexOptions.incremental` property is deprecated and it has no effect on the build process.
Error:Execution failed for task ':app:transformClassesWithDexForFullDebug'.
> JSR/RET are not supported with computeFrames option
Information:BUILD FAILED
Information:Total time: 33.919 secs
Information:1 error
Information:1 warning
Information:See complete output in console

这是我的gradle配置
    compileSdkVersion 25
    buildToolsVersion '25.0.2'

    defaultConfig {
        applicationId "com.cqxiaokang.cloudloan"
        minSdkVersion 17
        targetSdkVersion 25
        versionCode 1
        versionName "2.0.3"
        multiDexEnabled true
    }

**Comment by 317764920** [comment]
gradle版本有限制吗？
只能使用2.0.0？
我用的2.2.3

**Comment by farmerjohngit** [comment]
@317764920  见issue: #2

**Comment by farmerjohngit** [comment]
@317764920  支持android gradle插件2.0.0以上版本
