### ISSUE TITLE
执行gradlew acesoDebug报错

### ISSUE THREAD

**Issue by ghost** [meili/Aceso#9]
`D:\temp3\Aceso-master\aceso-demo-fix>gradlew acesoDebug
To honour the JVM settings for this build a new JVM will be forked. Please consider using the daemon: https://docs.gradle.org/2.14.1/userguide/gradle_daemon.html.
Incremental java compilation is an incubating feature.                                 
blackList file is D:\temp3\Aceso-master\aceso-demo-fix\orign\aceso\instrument\full\debug\instrument.jar
next we will add all-classes.jar to the localJars.
the length of the array before and after comparison:  0 -> 1
next will be aceso fix.
next we will add all-classes.jar to the localJars.
the length of the array before and after comparison:  0 -> 1
next will be aceso fix.
find transform. class: class com.android.build.gradle.internal.transforms.DexTransform. task name: transformClassesWithDexForDebug
:acesoLib:preBuild UP-TO-DATE
:acesoLib:preReleaseBuild UP-TO-DATE
:acesoLib:checkReleaseManifest
:acesoLib:prepareReleaseDependencies
:acesoLib:compileReleaseAidl UP-TO-DATE
:acesoLib:compileReleaseNdk UP-TO-DATE
:acesoLib:compileLint UP-TO-DATE
:acesoLib:copyReleaseLint UP-TO-DATE
:acesoLib:mergeReleaseShaders UP-TO-DATE
:acesoLib:compileReleaseShaders UP-TO-DATE
:acesoLib:generateReleaseAssets UP-TO-DATE
:acesoLib:mergeReleaseAssets UP-TO-DATE
:acesoLib:mergeReleaseProguardFiles UP-TO-DATE
:acesoLib:packageReleaseRenderscript UP-TO-DATE
:acesoLib:compileReleaseRenderscript UP-TO-DATE      
:acesoLib:generateReleaseResValues UP-TO-DATE
:acesoLib:generateReleaseResources UP-TO-DATE
:acesoLib:packageReleaseResources UP-TO-DATE
:acesoLib:processReleaseManifest UP-TO-DATE
:acesoLib:generateReleaseBuildConfig UP-TO-DATE
:acesoLib:processReleaseResources UP-TO-DATE
:acesoLib:generateReleaseSources UP-TO-DATE
:acesoLib:incrementalReleaseJavaCompilationSafeguard UP-TO-DATE
:acesoLib:compileReleaseJavaWithJavac UP-TO-DATE
:acesoLib:processReleaseJavaRes UP-TO-DATE
:acesoLib:transformResourcesWithMergeJavaResForRelease UP-TO-DATE
:acesoLib:transformClassesAndResourcesWithSyncLibJarsForRelease UP-TO-DATE
:acesoLib:mergeReleaseJniLibFolders UP-TO-DATE
:acesoLib:transformNative_libsWithMergeJniLibsForRelease UP-TO-DATE
:acesoLib:transformNative_libsWithSyncJniLibsForRelease UP-TO-DATE
:acesoLib:bundleRelease UP-TO-DATE      
:app:preBuild UP-TO-DATE
:app:preDebugBuild UP-TO-DATE
:app:checkDebugManifest
:app:extractProguardFiles
:app:preReleaseBuild
:app:prepareComMogujieAcesoAcesoLib001Library UP-TO-DATE
:app:prepareDebugDependencies
:app:compileDebugAidl UP-TO-DATE
:app:compileDebugRenderscript UP-TO-DATE
:app:generateDebugBuildConfig UP-TO-DATE
:app:generateDebugResValues UP-TO-DATE
:app:generateDebugResources UP-TO-DATE
:app:mergeDebugResources UP-TO-DATE
:app:processDebugManifest UP-TO-DATE
:app:processDebugResources UP-TO-DATE
:app:generateDebugSources UP-TO-DATE
:app:incrementalDebugJavaCompilationSafeguard UP-TO-DATE
:app:compileDebugJavaWithJavac UP-TO-DATE
:app:compileDebugNdk UP-TO-DATE
:app:compileDebugSources UP-TO-DATE
:app:mergeDebugShaders UP-TO-DATE
:app:compileDebugShaders UP-TO-DATE
:app:generateDebugAssets UP-TO-DATE
:app:mergeDebugAssets UP-TO-DATE      
:app:transformClassesWithDexForDebug
add jar D:\temp3\Aceso-master\aceso-demo-fix\app\build\intermediates\exploded-aar\com.mogujie.aceso\acesoLib\0.0.1\jars\classes.jar
add dir D:\temp3\Aceso-master\aceso-demo-fix\app\build\intermediates\classes\debug
generate the fix class..                             
class com/android/annotations/concurrency/GuardedBy.class's mtd count : 0
class com/android/annotations/concurrency/Immutable.class's mtd count : 0
class com/android/annotations/FixMtd.class's mtd count : 0
class com/android/annotations/NonNull.class's mtd count : 0
class com/android/annotations/NonNullByDefault.class's mtd count : 0
class com/android/annotations/Nullable.class's mtd count : 0
IncrementalChangeVisitor: Visiting com/android/tools/fd/runtime/AbstractPatchesLoaderImpl
visit method <init>  ()V
visit method load  ()Z
:app:transformClassesWithDexForDebug FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:transformClassesWithDexForDebug'.
> can not find class: com/android/tools/fd/runtime/AbstractPatchesLoaderImpl , sure you aceso-mapping is right and this class not in blacklist.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED

Total time: 9.407 secs
`

**Comment by farmerjohngit** [comment]
@qkCoder 看log，你是让demo-fix工程直接compile 了acesoLib工程吧？ demo-fix工程不能直接依赖于lib工程的

**Comment by ghost** [comment]
@farmerjohngit 嗯，第一次集成。我主要看到demo-fix工程中会报错所以compile了lib. 如下这些地方：
`   new Aceso().installPatch(optDir, patchFile);`
`   @FixMtd
    public void test(View view) {
        Toast.makeText(this, "ChengDu Level !", Toast.LENGTH_SHORT).show();
    }`
不管错误，直接gradlew acesoDebug 成功打包了。默认生成的app-debug.apk，我copy到手机根目录，改名fix.apk，成功提示fixed。

**Comment by farmerjohngit** [comment]
@qkCoder 之前的demo-fix工程在ide中有些问题，这个mr已经修复了 #13
